application: tzwmtest
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: "2.5.1"
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
- name: jinja2
  version: "2.6"
- name: lxml
  version: '2.3'

inbound_services:
- xmpp_message

handlers:
- url: /.*
  script: main.py
